### ISSUE TITLE
support for reading <code> tags

### ISSUE THREAD

**Issue by sktguha** [cynthia/chromevox#1]
I was wondering if there was some support for special navigation of CODE tags , as I feel even some sighted  developers may hear code sometimes instead of reading , to give rest to their eyes.
I was wondering if any such study etc was done on how to read code properly by a screenreader
Thanks

**Comment by cynthia** [comment]
As for the question - no, I don't think there is any special support for it. This would be a complex topic as programming languages are logically perceived in different ways from how it is straight up written, so it'll most likely have to be context aware.

Aside from that, this is not the official Chromevox repository, it's a clone of the official subversion repository and is neither endorsed nor supported by Google. You'll need to ask people on the official mailing list to discuss feature requests.
